export { default as Login } from './Login';
export { default as HomeAdm } from './HomeAdm';
export { default as Profile } from './Profile';
export { default as Material } from './Material/Material';
export { default as Home } from './Home';
export { default as Course } from './Course';
export { default as CourseById } from './CourseById';
export { default as User } from './User';
export { default as Notifications } from './Notifications';
