export * from './Input';
export * from './Header/Header';
export * from './If';
export { default as Modal } from './Modal';
export * from './UsersTable';
export * from './Button';
export * from './Menu';
export * from './Recharts';
export * from './LoadingPage';
export * from './CourseCard';
export * from './Activities';
export * from './UsersCard';
export * from './InputText';
export * from './Toggle';
export * from './RemoveUserModal';
export { default as UpdateUserModal } from './UpdateUserModal';
export { default as CreateUserModal } from './CreateUserModal';
export { default as CreateCourseModal } from './CreateCourseModal';
export * from './RemoveCourseModal';
export { default as UpdateCourseModal } from './UpdateCourseModal';
export { default as CreateMaterialModal } from './CreateMaterialModal';
