name: Check

on:
  push:
    branchs: [main, master]
  pull_request:
    branchs: [main, master]

jobs:
  code:
    name: lintcode
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: eslint
        run: yarn lint